retail_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'retail_user') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'retail_pass') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('DBT_POSTGRES_DBNAME', 'retail_db') }}"
      schema: raw
      threads: 4
